
'use strict';

{/* Sample crossword format. Actual words have been auto selected/generated by a basic algorithm just to demonstrate the input JSON format*/}

module.exports = {
    loadCW: () => {
    return {
            "cw":
            {
            "a":[
                {"w":"operative","d":" effective","c":"1-4"},
                {"w":"wash","d":" be capable of being washed","c":"3-2"},
                {"w":"androgyny","d":" showing characteristics of both sexes  ","c":"5-4"},
                {"w":"bromine","d":" found in sea water  ","c":"7-5"},
                {"w":"absolutism","d":" dominance through threat of punishment and violence  ","c":"9-3"},
                {"w":"anise","d":" native to Egypt but cultivated widely for its aromatic seeds and the oil from them used medicinally and as a flavoring in cookery  ","c":"11-1"}
                ],
            "d":[
                {"w":"anathema","d":" \"he is an anathema to me\"  ","c":"4-1"},
                {"w":"Abnaki","d":" of or relating to the Abnakis or their language  ","c":"6-3"},
                {"w":"run","d":" \"the story or argument runs as follows\"","c":"1-7"},
                {"w":"rootlet","d":" small root or division of a root  ","c":"5-7"},
                {"w":"vegan","d":" someone who eats no animal or dairy products at all  ","c":"1-11"},
                {"w":"east","d":" to, toward, or in the east","c":"7-11"}
                ]
            }
        }    
    
    }
};